version: "3.2"
services:
  7dtd:
    build:
      context: .
    image: 7dtd:latest
    container_name: 7dtd
    ports:
      - 2100:2100
    environment:
      - instance_name=instance1
    volumes: 
      - type: bind
        source: ./sdtd/data
        target: /home/sdtd
    restart: always
